### ISSUE TITLE
IsoformSwitch vs Stringtie results differ

### ISSUE THREAD

**Issue by agoldkamp** [kvittingseerup/IsoformSwitchAnalyzeR#160] opened 2023-01-30 19:28 UTC
We are really interested in using IsoformSwitch in our analysis. However, our results are showing differences that we cannot explain. I have attached a picture of some of the results as an example.

After using IsoformSwitch and running edgeR, two genes (MIR2410 and MIR2474) are significant with a logFoldChange of ~7. However, if we use the stringtie output (before IsoformSwitch) and run edgeR, we find that they are non-significant with logFoldChange of ~4. Could you help us understand how the reads are assigned to the genes with IsoformSwitch and why we might be getting these results?
<img width="682" alt="Screen Shot 2023-01-30 at 1 25 31 PM" src="https://user-images.githubusercontent.com/87573789/215576168-c83090b4-1b49-4820-b3f0-b4655cf4f624.png">

**Comment by agoldkamp** [comment] 2023-01-30 19:33
Let me provide more information about our pipeline:

For generating the stringtie count table,

**1.	We first assembled and merged the transcripts, creating a gtf file for each individual:**
stringtie -o ./stringtie_gtf/HC0301955_stringtie.gtf --rf -p 16 -G GCF_002263795.1_ARS-UCD1.2_genomic.gff ./Bam_files/HC0301955.sorted.bam

**2.	We then merged gtf files:**
stringtie --merge -p 12 -G GCF_002263795.1_ARS-UCD1.2_genomic.gff -o stringtie_merged.gtf gtf_list.txt

**3.	Next, we estimated abundance:**
stringtie -e -B -p 8 -G stringtie_merged.gtf -o ./final_gtf_DE/HC0301955/HC0301955_DE.gtf ./Bam_files/HC0301955.sorted.bam

**4.	Finally, we used the prepDE.py script in order to generate a raw count matrix for genes. PrepDE.py uses the individual gtf files generated in the previous step (final_gtf_DE/HC0301955/HC0301955_DE.gtf)to generate counts.**
python prepDE.py -i final_gtf_DE

For generating the IsoformSwitch count table we used the following code:

**### Import StringTie Expression data**
stringTieQuant <- importIsoformExpression(
  parentDir = "/Users/annagoldkamp/Desktop/IsoformSwitchAnalyzeR/final_gtf_DE/",
  addIsofomIdAsColumn = FALSE,
  readLength = 150)


**### Make design matrix**
myDesign <- data.frame(
  sampleID = colnames(stringTieQuant$abundance),
  condition = gsub('_.*', '', colnames(stringTieQuant$abundance)))


**### Create switchAnalyzeRlist**
switchAnalyzeRlist <- importRdata(
  isoformCountMatrix   = stringTieQuant$counts,
  isoformRepExpression = stringTieQuant$abundance,
  designMatrix         = myDesign_new,
  isoformExonAnnoation = "/Users/annagoldkamp/Desktop/IsoformSwitchAnalyzeR/stringtie_merged.gtf")

**### Extract gene count matrix**
geneCountMatrix <- extractGeneExpression(
  switchAnalyzeRlist,
  extractCounts = TRUE # set to FALSE for abundances
)

-In this case, IsoformSwitch uses the t_data.ctab inside of the final_gtf_DE directory for each sample instead of HC0301955_DE.gtf. It appears that both files have the same coverage and FPKM information for transcripts.


Please let me know if I can provide any other information to help understand the differences in counts between the two methods.

Thank you,
Anna

**Comment by kvittingseerup** [comment] 2023-01-31 12:03
The problem is that you compare two different count matrixes - the one generated by `importIsoformExpression()` (which under the hoot uses `tximport()`) and the one generated by `prepDE.py`. This is further exacerbated by the read length problem where you specify the read length for `importIsoformExpression()` but not for `prepDE.py`.

The underlying problem is that StringTie does not actually count reads - it estimates coverage - and `importIsoformExpression()` and `prepDE.py` back-calculate the read count using the read length.

It is a rabbit hole you can spend a lot of time investigating and figuring out what a good approach are. After I did that my new recommendation is that you replace your third step (the quantification) with a quantification using Salmon/Kallisto using the merged transcriptome from step 2 to build your index. Alternatively, I recommend `importIsoformExpression()` paying attention to the `readLength` argument which should be the total length of the reads (so if you sequenced 75nt single end it is 75. If you sequenced 75nt paired end it should be 150.)

**Closed by kvittingseerup** 2023-01-31 12:03 UTC
